before_script:
  - git log -n 3
  - git push --mirror git@github.com:Devintia/Commons.git
build_commons:
  stage: build
  script:
    - mvn clean deploy
  artifacts:
    paths:
      - '**/target/*.jar'
build_docker:
  stage: deploy
  script:
    - "curl -X POST -F token=$DOCKER_BUILD_TOKEN -F ref=master http://git.devintia.net/api/v3/projects/1/trigger/builds"